version: '3.7'

volumes:
  ts-db:

services:
  ts-postgres:
    container_name: Ticket_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    volumes:
      - ts-db:/var/lib/postgresql/data
    ports:
      - "5439:5432"