version: '3.7'

volumes:
  ts-db:

services:
  ts-postgres:
    container_name: EuroTruckSimulator
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: game_db
    volumes:
      - ts-db:/var/lib/postgresql/data
    ports:
      - "5442:5432"