version: '3.7'

volumes:
  ts-db:

services:
  ts-postgres:
    container_name: dz_10_container
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dz10_db
    volumes:
      - ts-db:/var/lib/postgresql/data
    ports:
      - "5440:5432"